[build]
  command = "CI=false npm install && npx tailwindcss init -p && npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://dashboard-gmvy.onrender.com"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"