[build]
  command = "npm install --save-dev typescript @types/node @types/react @types/react-dom && npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://dashboard-gmvy.onrender.com"
  NODE_ENV = "production"